// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mock_server is a generated GoMock package.
package mock_server

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	loader "github.com/mamonth/oasmock/internal/loader"
	runtime "github.com/mamonth/oasmock/internal/runtime"
	server "github.com/mamonth/oasmock/internal/server"
)

// MockRouteProvider is a mock of RouteProvider interface.
type MockRouteProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRouteProviderMockRecorder
}

// MockRouteProviderMockRecorder is the mock recorder for MockRouteProvider.
type MockRouteProviderMockRecorder struct {
	mock *MockRouteProvider
}

// NewMockRouteProvider creates a new mock instance.
func NewMockRouteProvider(ctrl *gomock.Controller) *MockRouteProvider {
	mock := &MockRouteProvider{ctrl: ctrl}
	mock.recorder = &MockRouteProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouteProvider) EXPECT() *MockRouteProviderMockRecorder {
	return m.recorder
}

// BuildRouteMappings mocks base method.
func (m *MockRouteProvider) BuildRouteMappings(schemas []server.SchemaInfo) ([]server.RouteMapping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildRouteMappings", schemas)
	ret0, _ := ret[0].([]server.RouteMapping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildRouteMappings indicates an expected call of BuildRouteMappings.
func (mr *MockRouteProviderMockRecorder) BuildRouteMappings(schemas interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildRouteMappings", reflect.TypeOf((*MockRouteProvider)(nil).BuildRouteMappings), schemas)
}

// MockStateStore is a mock of StateStore interface.
type MockStateStore struct {
	ctrl     *gomock.Controller
	recorder *MockStateStoreMockRecorder
}

// MockStateStoreMockRecorder is the mock recorder for MockStateStore.
type MockStateStoreMockRecorder struct {
	mock *MockStateStore
}

// NewMockStateStore creates a new mock instance.
func NewMockStateStore(ctrl *gomock.Controller) *MockStateStore {
	mock := &MockStateStore{ctrl: ctrl}
	mock.recorder = &MockStateStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateStore) EXPECT() *MockStateStoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockStateStore) Delete(namespace, key string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", namespace, key)
}

// Delete indicates an expected call of Delete.
func (mr *MockStateStoreMockRecorder) Delete(namespace, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStateStore)(nil).Delete), namespace, key)
}

// Get mocks base method.
func (m *MockStateStore) Get(namespace, key string) (any, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", namespace, key)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStateStoreMockRecorder) Get(namespace, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStateStore)(nil).Get), namespace, key)
}

// GetAll mocks base method.
func (m *MockStateStore) GetAll() map[string]map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(map[string]map[string]any)
	return ret0
}

// GetAll indicates an expected call of GetAll.
func (mr *MockStateStoreMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockStateStore)(nil).GetAll))
}

// GetNamespace mocks base method.
func (m *MockStateStore) GetNamespace(namespace string) map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespace", namespace)
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// GetNamespace indicates an expected call of GetNamespace.
func (mr *MockStateStoreMockRecorder) GetNamespace(namespace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespace", reflect.TypeOf((*MockStateStore)(nil).GetNamespace), namespace)
}

// Increment mocks base method.
func (m *MockStateStore) Increment(namespace, key string, delta float64) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Increment", namespace, key, delta)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Increment indicates an expected call of Increment.
func (mr *MockStateStoreMockRecorder) Increment(namespace, key, delta interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Increment", reflect.TypeOf((*MockStateStore)(nil).Increment), namespace, key, delta)
}

// Set mocks base method.
func (m *MockStateStore) Set(namespace, key string, value any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", namespace, key, value)
}

// Set indicates an expected call of Set.
func (mr *MockStateStoreMockRecorder) Set(namespace, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockStateStore)(nil).Set), namespace, key, value)
}

// MockHistoryStore is a mock of HistoryStore interface.
type MockHistoryStore struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryStoreMockRecorder
}

// MockHistoryStoreMockRecorder is the mock recorder for MockHistoryStore.
type MockHistoryStoreMockRecorder struct {
	mock *MockHistoryStore
}

// NewMockHistoryStore creates a new mock instance.
func NewMockHistoryStore(ctrl *gomock.Controller) *MockHistoryStore {
	mock := &MockHistoryStore{ctrl: ctrl}
	mock.recorder = &MockHistoryStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoryStore) EXPECT() *MockHistoryStoreMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockHistoryStore) Add(record server.RequestRecord) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", record)
}

// Add indicates an expected call of Add.
func (mr *MockHistoryStoreMockRecorder) Add(record interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockHistoryStore)(nil).Add), record)
}

// Capacity mocks base method.
func (m *MockHistoryStore) Capacity() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Capacity")
	ret0, _ := ret[0].(int)
	return ret0
}

// Capacity indicates an expected call of Capacity.
func (mr *MockHistoryStoreMockRecorder) Capacity() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Capacity", reflect.TypeOf((*MockHistoryStore)(nil).Capacity))
}

// Clear mocks base method.
func (m *MockHistoryStore) Clear() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Clear")
}

// Clear indicates an expected call of Clear.
func (mr *MockHistoryStoreMockRecorder) Clear() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockHistoryStore)(nil).Clear))
}

// Count mocks base method.
func (m *MockHistoryStore) Count() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count")
	ret0, _ := ret[0].(int)
	return ret0
}

// Count indicates an expected call of Count.
func (mr *MockHistoryStoreMockRecorder) Count() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockHistoryStore)(nil).Count))
}

// GetAll mocks base method.
func (m *MockHistoryStore) GetAll() []server.RequestRecord {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]server.RequestRecord)
	return ret0
}

// GetAll indicates an expected call of GetAll.
func (mr *MockHistoryStoreMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockHistoryStore)(nil).GetAll))
}

// MockRpcProtocol is a mock of RpcProtocol interface.
type MockRpcProtocol struct {
	ctrl     *gomock.Controller
	recorder *MockRpcProtocolMockRecorder
}

// MockRpcProtocolMockRecorder is the mock recorder for MockRpcProtocol.
type MockRpcProtocolMockRecorder struct {
	mock *MockRpcProtocol
}

// NewMockRpcProtocol creates a new mock instance.
func NewMockRpcProtocol(ctrl *gomock.Controller) *MockRpcProtocol {
	mock := &MockRpcProtocol{ctrl: ctrl}
	mock.recorder = &MockRpcProtocolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRpcProtocol) EXPECT() *MockRpcProtocolMockRecorder {
	return m.recorder
}

// ContentType mocks base method.
func (m *MockRpcProtocol) ContentType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContentType")
	ret0, _ := ret[0].(string)
	return ret0
}

// ContentType indicates an expected call of ContentType.
func (mr *MockRpcProtocolMockRecorder) ContentType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContentType", reflect.TypeOf((*MockRpcProtocol)(nil).ContentType))
}

// ErrorResponse mocks base method.
func (m *MockRpcProtocol) ErrorResponse(code int, message string, id any) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ErrorResponse", code, message, id)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// ErrorResponse indicates an expected call of ErrorResponse.
func (mr *MockRpcProtocolMockRecorder) ErrorResponse(code, message, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorResponse", reflect.TypeOf((*MockRpcProtocol)(nil).ErrorResponse), code, message, id)
}

// ParseBody mocks base method.
func (m *MockRpcProtocol) ParseBody(body []byte) ([]server.RpcEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseBody", body)
	ret0, _ := ret[0].([]server.RpcEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseBody indicates an expected call of ParseBody.
func (mr *MockRpcProtocolMockRecorder) ParseBody(body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseBody", reflect.TypeOf((*MockRpcProtocol)(nil).ParseBody), body)
}

// MockMessageRenderer is a mock of MessageRenderer interface.
type MockMessageRenderer struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRendererMockRecorder
}

// MockMessageRendererMockRecorder is the mock recorder for MockMessageRenderer.
type MockMessageRendererMockRecorder struct {
	mock *MockMessageRenderer
}

// NewMockMessageRenderer creates a new mock instance.
func NewMockMessageRenderer(ctrl *gomock.Controller) *MockMessageRenderer {
	mock := &MockMessageRenderer{ctrl: ctrl}
	mock.recorder = &MockMessageRendererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRenderer) EXPECT() *MockMessageRendererMockRecorder {
	return m.recorder
}

// ApplySetState mocks base method.
func (m *MockMessageRenderer) ApplySetState(stateMap map[string]any, eval runtime.Evaluator, prefix string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ApplySetState", stateMap, eval, prefix)
}

// ApplySetState indicates an expected call of ApplySetState.
func (mr *MockMessageRendererMockRecorder) ApplySetState(stateMap, eval, prefix interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplySetState", reflect.TypeOf((*MockMessageRenderer)(nil).ApplySetState), stateMap, eval, prefix)
}

// NewEnvSource mocks base method.
func (m *MockMessageRenderer) NewEnvSource() *runtime.EnvSource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewEnvSource")
	ret0, _ := ret[0].(*runtime.EnvSource)
	return ret0
}

// NewEnvSource indicates an expected call of NewEnvSource.
func (mr *MockMessageRendererMockRecorder) NewEnvSource() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewEnvSource", reflect.TypeOf((*MockMessageRenderer)(nil).NewEnvSource))
}

// NewStateSource mocks base method.
func (m *MockMessageRenderer) NewStateSource(prefix string) *runtime.StateSource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewStateSource", prefix)
	ret0, _ := ret[0].(*runtime.StateSource)
	return ret0
}

// NewStateSource indicates an expected call of NewStateSource.
func (mr *MockMessageRendererMockRecorder) NewStateSource(prefix interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewStateSource", reflect.TypeOf((*MockMessageRenderer)(nil).NewStateSource), prefix)
}

// RenderAsyncPayload mocks base method.
func (m *MockMessageRenderer) RenderAsyncPayload(example *server.MessageExampleView, evaluator runtime.Evaluator) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderAsyncPayload", example, evaluator)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenderAsyncPayload indicates an expected call of RenderAsyncPayload.
func (mr *MockMessageRendererMockRecorder) RenderAsyncPayload(example, evaluator interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderAsyncPayload", reflect.TypeOf((*MockMessageRenderer)(nil).RenderAsyncPayload), example, evaluator)
}

// RenderMessageSpecs mocks base method.
func (m *MockMessageRenderer) RenderMessageSpecs(messages []*loader.MessageSpec, prefix, opID string, in server.InboundMessage) (int, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderMessageSpecs", messages, prefix, opID, in)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RenderMessageSpecs indicates an expected call of RenderMessageSpecs.
func (mr *MockMessageRendererMockRecorder) RenderMessageSpecs(messages, prefix, opID, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderMessageSpecs", reflect.TypeOf((*MockMessageRenderer)(nil).RenderMessageSpecs), messages, prefix, opID, in)
}

// SelectAsyncExample mocks base method.
func (m *MockMessageRenderer) SelectAsyncExample(message *loader.MessageSpec, evaluator runtime.Evaluator, opID string) (*server.MessageExampleView, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAsyncExample", message, evaluator, opID)
	ret0, _ := ret[0].(*server.MessageExampleView)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// SelectAsyncExample indicates an expected call of SelectAsyncExample.
func (mr *MockMessageRendererMockRecorder) SelectAsyncExample(message, evaluator, opID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAsyncExample", reflect.TypeOf((*MockMessageRenderer)(nil).SelectAsyncExample), message, evaluator, opID)
}

// MockConsumerBus is a mock of ConsumerBus interface.
type MockConsumerBus struct {
	ctrl     *gomock.Controller
	recorder *MockConsumerBusMockRecorder
}

// MockConsumerBusMockRecorder is the mock recorder for MockConsumerBus.
type MockConsumerBusMockRecorder struct {
	mock *MockConsumerBus
}

// NewMockConsumerBus creates a new mock instance.
func NewMockConsumerBus(ctrl *gomock.Controller) *MockConsumerBus {
	mock := &MockConsumerBus{ctrl: ctrl}
	mock.recorder = &MockConsumerBusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsumerBus) EXPECT() *MockConsumerBusMockRecorder {
	return m.recorder
}

// Candidates mocks base method.
func (m *MockConsumerBus) Candidates(address string) []server.ConsumerInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Candidates", address)
	ret0, _ := ret[0].([]server.ConsumerInfo)
	return ret0
}

// Candidates indicates an expected call of Candidates.
func (mr *MockConsumerBusMockRecorder) Candidates(address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Candidates", reflect.TypeOf((*MockConsumerBus)(nil).Candidates), address)
}

// PushTo mocks base method.
func (m *MockConsumerBus) PushTo(consumer server.ConsumerInfo, address string, payload []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PushTo", consumer, address, payload)
}

// PushTo indicates an expected call of PushTo.
func (mr *MockConsumerBusMockRecorder) PushTo(consumer, address, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushTo", reflect.TypeOf((*MockConsumerBus)(nil).PushTo), consumer, address, payload)
}

// SignalRPush mocks base method.
func (m *MockConsumerBus) SignalRPush(address string, payload []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SignalRPush", address, payload)
}

// SignalRPush indicates an expected call of SignalRPush.
func (mr *MockConsumerBusMockRecorder) SignalRPush(address, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignalRPush", reflect.TypeOf((*MockConsumerBus)(nil).SignalRPush), address, payload)
}

// WSBroadcast mocks base method.
func (m *MockConsumerBus) WSBroadcast(address string, payload []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WSBroadcast", address, payload)
}

// WSBroadcast indicates an expected call of WSBroadcast.
func (mr *MockConsumerBusMockRecorder) WSBroadcast(address, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WSBroadcast", reflect.TypeOf((*MockConsumerBus)(nil).WSBroadcast), address, payload)
}
