// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mamonth/oasmock/internal/server (interfaces: RouteProvider,StateStore,HistoryStore,DataSource,RequestSourceFactory,StateSourceFactory,EnvSourceFactory,ExpressionEvaluator,ExtensionProcessor)

// Package server is a generated GoMock package.
package server

import (
	http "net/http"
	reflect "reflect"

	openapi3 "github.com/getkin/kin-openapi/openapi3"
	gomock "github.com/golang/mock/gomock"
)

// MockRouteProvider is a mock of RouteProvider interface.
type MockRouteProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRouteProviderMockRecorder
}

// MockRouteProviderMockRecorder is the mock recorder for MockRouteProvider.
type MockRouteProviderMockRecorder struct {
	mock *MockRouteProvider
}

// NewMockRouteProvider creates a new mock instance.
func NewMockRouteProvider(ctrl *gomock.Controller) *MockRouteProvider {
	mock := &MockRouteProvider{ctrl: ctrl}
	mock.recorder = &MockRouteProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouteProvider) EXPECT() *MockRouteProviderMockRecorder {
	return m.recorder
}

// BuildRouteMappings mocks base method.
func (m *MockRouteProvider) BuildRouteMappings(arg0 []SchemaInfo) ([]RouteMapping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildRouteMappings", arg0)
	ret0, _ := ret[0].([]RouteMapping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildRouteMappings indicates an expected call of BuildRouteMappings.
func (mr *MockRouteProviderMockRecorder) BuildRouteMappings(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildRouteMappings", reflect.TypeOf((*MockRouteProvider)(nil).BuildRouteMappings), arg0)
}

// MockStateStore is a mock of StateStore interface.
type MockStateStore struct {
	ctrl     *gomock.Controller
	recorder *MockStateStoreMockRecorder
}

// MockStateStoreMockRecorder is the mock recorder for MockStateStore.
type MockStateStoreMockRecorder struct {
	mock *MockStateStore
}

// NewMockStateStore creates a new mock instance.
func NewMockStateStore(ctrl *gomock.Controller) *MockStateStore {
	mock := &MockStateStore{ctrl: ctrl}
	mock.recorder = &MockStateStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateStore) EXPECT() *MockStateStoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockStateStore) Delete(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", arg0, arg1)
}

// Delete indicates an expected call of Delete.
func (mr *MockStateStoreMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStateStore)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockStateStore) Get(arg0, arg1 string) (interface{}, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStateStoreMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStateStore)(nil).Get), arg0, arg1)
}

// GetAll mocks base method.
func (m *MockStateStore) GetAll() map[string]map[string]interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(map[string]map[string]interface{})
	return ret0
}

// GetAll indicates an expected call of GetAll.
func (mr *MockStateStoreMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockStateStore)(nil).GetAll))
}

// GetNamespace mocks base method.
func (m *MockStateStore) GetNamespace(arg0 string) map[string]interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespace", arg0)
	ret0, _ := ret[0].(map[string]interface{})
	return ret0
}

// GetNamespace indicates an expected call of GetNamespace.
func (mr *MockStateStoreMockRecorder) GetNamespace(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespace", reflect.TypeOf((*MockStateStore)(nil).GetNamespace), arg0)
}

// Increment mocks base method.
func (m *MockStateStore) Increment(arg0, arg1 string, arg2 float64) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Increment", arg0, arg1, arg2)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Increment indicates an expected call of Increment.
func (mr *MockStateStoreMockRecorder) Increment(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Increment", reflect.TypeOf((*MockStateStore)(nil).Increment), arg0, arg1, arg2)
}

// Set mocks base method.
func (m *MockStateStore) Set(arg0, arg1 string, arg2 interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", arg0, arg1, arg2)
}

// Set indicates an expected call of Set.
func (mr *MockStateStoreMockRecorder) Set(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockStateStore)(nil).Set), arg0, arg1, arg2)
}

// MockHistoryStore is a mock of HistoryStore interface.
type MockHistoryStore struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryStoreMockRecorder
}

// MockHistoryStoreMockRecorder is the mock recorder for MockHistoryStore.
type MockHistoryStoreMockRecorder struct {
	mock *MockHistoryStore
}

// NewMockHistoryStore creates a new mock instance.
func NewMockHistoryStore(ctrl *gomock.Controller) *MockHistoryStore {
	mock := &MockHistoryStore{ctrl: ctrl}
	mock.recorder = &MockHistoryStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoryStore) EXPECT() *MockHistoryStoreMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockHistoryStore) Add(arg0 RequestRecord) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", arg0)
}

// Add indicates an expected call of Add.
func (mr *MockHistoryStoreMockRecorder) Add(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockHistoryStore)(nil).Add), arg0)
}

// Capacity mocks base method.
func (m *MockHistoryStore) Capacity() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Capacity")
	ret0, _ := ret[0].(int)
	return ret0
}

// Capacity indicates an expected call of Capacity.
func (mr *MockHistoryStoreMockRecorder) Capacity() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Capacity", reflect.TypeOf((*MockHistoryStore)(nil).Capacity))
}

// Clear mocks base method.
func (m *MockHistoryStore) Clear() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Clear")
}

// Clear indicates an expected call of Clear.
func (mr *MockHistoryStoreMockRecorder) Clear() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockHistoryStore)(nil).Clear))
}

// Count mocks base method.
func (m *MockHistoryStore) Count() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count")
	ret0, _ := ret[0].(int)
	return ret0
}

// Count indicates an expected call of Count.
func (mr *MockHistoryStoreMockRecorder) Count() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockHistoryStore)(nil).Count))
}

// GetAll mocks base method.
func (m *MockHistoryStore) GetAll() []RequestRecord {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]RequestRecord)
	return ret0
}

// GetAll indicates an expected call of GetAll.
func (mr *MockHistoryStoreMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockHistoryStore)(nil).GetAll))
}

// MockDataSource is a mock of DataSource interface.
type MockDataSource struct {
	ctrl     *gomock.Controller
	recorder *MockDataSourceMockRecorder
}

// MockDataSourceMockRecorder is the mock recorder for MockDataSource.
type MockDataSourceMockRecorder struct {
	mock *MockDataSource
}

// NewMockDataSource creates a new mock instance.
func NewMockDataSource(ctrl *gomock.Controller) *MockDataSource {
	mock := &MockDataSource{ctrl: ctrl}
	mock.recorder = &MockDataSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataSource) EXPECT() *MockDataSourceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockDataSource) Get(arg0 string) (interface{}, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDataSourceMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDataSource)(nil).Get), arg0)
}

// MockRequestSourceFactory is a mock of RequestSourceFactory interface.
type MockRequestSourceFactory struct {
	ctrl     *gomock.Controller
	recorder *MockRequestSourceFactoryMockRecorder
}

// MockRequestSourceFactoryMockRecorder is the mock recorder for MockRequestSourceFactory.
type MockRequestSourceFactoryMockRecorder struct {
	mock *MockRequestSourceFactory
}

// NewMockRequestSourceFactory creates a new mock instance.
func NewMockRequestSourceFactory(ctrl *gomock.Controller) *MockRequestSourceFactory {
	mock := &MockRequestSourceFactory{ctrl: ctrl}
	mock.recorder = &MockRequestSourceFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestSourceFactory) EXPECT() *MockRequestSourceFactoryMockRecorder {
	return m.recorder
}

// NewRequestSource mocks base method.
func (m *MockRequestSourceFactory) NewRequestSource(arg0 *http.Request, arg1 map[string]string) DataSource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRequestSource", arg0, arg1)
	ret0, _ := ret[0].(DataSource)
	return ret0
}

// NewRequestSource indicates an expected call of NewRequestSource.
func (mr *MockRequestSourceFactoryMockRecorder) NewRequestSource(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRequestSource", reflect.TypeOf((*MockRequestSourceFactory)(nil).NewRequestSource), arg0, arg1)
}

// MockStateSourceFactory is a mock of StateSourceFactory interface.
type MockStateSourceFactory struct {
	ctrl     *gomock.Controller
	recorder *MockStateSourceFactoryMockRecorder
}

// MockStateSourceFactoryMockRecorder is the mock recorder for MockStateSourceFactory.
type MockStateSourceFactoryMockRecorder struct {
	mock *MockStateSourceFactory
}

// NewMockStateSourceFactory creates a new mock instance.
func NewMockStateSourceFactory(ctrl *gomock.Controller) *MockStateSourceFactory {
	mock := &MockStateSourceFactory{ctrl: ctrl}
	mock.recorder = &MockStateSourceFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateSourceFactory) EXPECT() *MockStateSourceFactoryMockRecorder {
	return m.recorder
}

// NewStateSource mocks base method.
func (m *MockStateSourceFactory) NewStateSource(arg0 string) DataSource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewStateSource", arg0)
	ret0, _ := ret[0].(DataSource)
	return ret0
}

// NewStateSource indicates an expected call of NewStateSource.
func (mr *MockStateSourceFactoryMockRecorder) NewStateSource(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewStateSource", reflect.TypeOf((*MockStateSourceFactory)(nil).NewStateSource), arg0)
}

// MockEnvSourceFactory is a mock of EnvSourceFactory interface.
type MockEnvSourceFactory struct {
	ctrl     *gomock.Controller
	recorder *MockEnvSourceFactoryMockRecorder
}

// MockEnvSourceFactoryMockRecorder is the mock recorder for MockEnvSourceFactory.
type MockEnvSourceFactoryMockRecorder struct {
	mock *MockEnvSourceFactory
}

// NewMockEnvSourceFactory creates a new mock instance.
func NewMockEnvSourceFactory(ctrl *gomock.Controller) *MockEnvSourceFactory {
	mock := &MockEnvSourceFactory{ctrl: ctrl}
	mock.recorder = &MockEnvSourceFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnvSourceFactory) EXPECT() *MockEnvSourceFactoryMockRecorder {
	return m.recorder
}

// NewEnvSource mocks base method.
func (m *MockEnvSourceFactory) NewEnvSource() DataSource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewEnvSource")
	ret0, _ := ret[0].(DataSource)
	return ret0
}

// NewEnvSource indicates an expected call of NewEnvSource.
func (mr *MockEnvSourceFactoryMockRecorder) NewEnvSource() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewEnvSource", reflect.TypeOf((*MockEnvSourceFactory)(nil).NewEnvSource))
}

// MockExpressionEvaluator is a mock of ExpressionEvaluator interface.
type MockExpressionEvaluator struct {
	ctrl     *gomock.Controller
	recorder *MockExpressionEvaluatorMockRecorder
}

// MockExpressionEvaluatorMockRecorder is the mock recorder for MockExpressionEvaluator.
type MockExpressionEvaluatorMockRecorder struct {
	mock *MockExpressionEvaluator
}

// NewMockExpressionEvaluator creates a new mock instance.
func NewMockExpressionEvaluator(ctrl *gomock.Controller) *MockExpressionEvaluator {
	mock := &MockExpressionEvaluator{ctrl: ctrl}
	mock.recorder = &MockExpressionEvaluatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExpressionEvaluator) EXPECT() *MockExpressionEvaluatorMockRecorder {
	return m.recorder
}

// AddSource mocks base method.
func (m *MockExpressionEvaluator) AddSource(arg0 string, arg1 DataSource) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddSource", arg0, arg1)
}

// AddSource indicates an expected call of AddSource.
func (mr *MockExpressionEvaluatorMockRecorder) AddSource(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSource", reflect.TypeOf((*MockExpressionEvaluator)(nil).AddSource), arg0, arg1)
}

// Evaluate mocks base method.
func (m *MockExpressionEvaluator) Evaluate(arg0 string) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", arg0)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockExpressionEvaluatorMockRecorder) Evaluate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockExpressionEvaluator)(nil).Evaluate), arg0)
}

// MockExtensionProcessor is a mock of ExtensionProcessor interface.
type MockExtensionProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionProcessorMockRecorder
}

// MockExtensionProcessorMockRecorder is the mock recorder for MockExtensionProcessor.
type MockExtensionProcessorMockRecorder struct {
	mock *MockExtensionProcessor
}

// NewMockExtensionProcessor creates a new mock instance.
func NewMockExtensionProcessor(ctrl *gomock.Controller) *MockExtensionProcessor {
	mock := &MockExtensionProcessor{ctrl: ctrl}
	mock.recorder = &MockExtensionProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionProcessor) EXPECT() *MockExtensionProcessorMockRecorder {
	return m.recorder
}

// EvaluateParamsMatch mocks base method.
func (m *MockExtensionProcessor) EvaluateParamsMatch(arg0 map[string]interface{}, arg1 ExpressionEvaluator) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvaluateParamsMatch", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EvaluateParamsMatch indicates an expected call of EvaluateParamsMatch.
func (mr *MockExtensionProcessorMockRecorder) EvaluateParamsMatch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvaluateParamsMatch", reflect.TypeOf((*MockExtensionProcessor)(nil).EvaluateParamsMatch), arg0, arg1)
}

// ExtractHeaders mocks base method.
func (m *MockExtensionProcessor) ExtractHeaders(arg0 *openapi3.Example) (map[string]interface{}, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractHeaders", arg0)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ExtractHeaders indicates an expected call of ExtractHeaders.
func (mr *MockExtensionProcessorMockRecorder) ExtractHeaders(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractHeaders", reflect.TypeOf((*MockExtensionProcessor)(nil).ExtractHeaders), arg0)
}

// ExtractOnce mocks base method.
func (m *MockExtensionProcessor) ExtractOnce(arg0 *openapi3.Example) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractOnce", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ExtractOnce indicates an expected call of ExtractOnce.
func (mr *MockExtensionProcessorMockRecorder) ExtractOnce(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractOnce", reflect.TypeOf((*MockExtensionProcessor)(nil).ExtractOnce), arg0)
}

// ExtractParamsMatch mocks base method.
func (m *MockExtensionProcessor) ExtractParamsMatch(arg0 *openapi3.Example) (map[string]interface{}, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractParamsMatch", arg0)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ExtractParamsMatch indicates an expected call of ExtractParamsMatch.
func (mr *MockExtensionProcessorMockRecorder) ExtractParamsMatch(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractParamsMatch", reflect.TypeOf((*MockExtensionProcessor)(nil).ExtractParamsMatch), arg0)
}

// ExtractSetState mocks base method.
func (m *MockExtensionProcessor) ExtractSetState(arg0 *openapi3.Example) (map[string]interface{}, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractSetState", arg0)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ExtractSetState indicates an expected call of ExtractSetState.
func (mr *MockExtensionProcessorMockRecorder) ExtractSetState(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractSetState", reflect.TypeOf((*MockExtensionProcessor)(nil).ExtractSetState), arg0)
}

// ExtractSkip mocks base method.
func (m *MockExtensionProcessor) ExtractSkip(arg0 *openapi3.Example) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractSkip", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ExtractSkip indicates an expected call of ExtractSkip.
func (mr *MockExtensionProcessorMockRecorder) ExtractSkip(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractSkip", reflect.TypeOf((*MockExtensionProcessor)(nil).ExtractSkip), arg0)
}
