package main

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

/*
Scenario: Dereferencing a component schema graph into a standalone schema
Given a map of component schemas where AddExampleRequest references two concrete

	schemas via oneOf, each merging a shared base through allOf

When deref is applied to AddExampleRequest
Then every $ref within components/schemas is inlined, the shared base and the

	not-fences are preserved, and no $ref remains

Related spec scenarios: RS.MAPI.14, RS.MAPI.27, RS.MAPI.28
*/
func TestDerefInlinesComponentRefs(t *testing.T) {
	t.Parallel()

	schemas := map[string]any{
		"NewExampleRequestBase": map[string]any{
			"type":     "object",
			"required": []any{"response"},
			"properties": map[string]any{
				"method": map[string]any{"type": "string"},
			},
		},
		"NewExampleRequestSync": map[string]any{
			"type":  "object",
			"allOf": []any{map[string]any{"$ref": "#/components/schemas/NewExampleRequestBase"}},
		},
		"NewExampleRequestAsync": map[string]any{
			"type":  "object",
			"allOf": []any{map[string]any{"$ref": "#/components/schemas/NewExampleRequestBase"}},
		},
		"AddExampleRequest": map[string]any{
			"oneOf": []any{
				map[string]any{"$ref": "#/components/schemas/NewExampleRequestSync"},
				map[string]any{"$ref": "#/components/schemas/NewExampleRequestAsync"},
			},
		},
	}

	resolved, err := deref(schemas["AddExampleRequest"], schemas)
	require.NoError(t, err)
	assert.False(t, containsRef(resolved), "all component refs must be inlined")

	raw, err := json.Marshal(resolved)
	require.NoError(t, err)
	var doc map[string]any
	require.NoError(t, json.Unmarshal(raw, &doc))

	oneOf, ok := doc["oneOf"].([]any)
	require.True(t, ok, "resolved schema must keep its oneOf")
	require.Len(t, oneOf, 2)
	for _, branch := range oneOf {
		branchMap, ok := branch.(map[string]any)
		require.True(t, ok)
		allOf, ok := branchMap["allOf"].([]any)
		require.True(t, ok, "concrete branches must merge the base through allOf")
		require.Len(t, allOf, 1)
		base, ok := allOf[0].(map[string]any)
		require.True(t, ok)
		assert.NotEmpty(t, base["properties"], "shared base properties must survive inlining")
	}
}

/*
Scenario: Leaving refs outside components.schemas untouched
Given a schema referencing an example resource outside components.schemas
When deref is applied
Then the external ref is preserved verbatim instead of failing

Related spec scenarios: RS.MAPI.14
*/
func TestDerefPreservesExternalRefs(t *testing.T) {
	t.Parallel()

	schemas := map[string]any{
		"AddExampleRequest": map[string]any{
			"oneOf": []any{
				map[string]any{
					"type":       "object",
					"properties": map[string]any{"$ref": "#/components/examples/someExample"},
				},
			},
		},
	}

	resolved, err := deref(schemas["AddExampleRequest"], schemas)
	require.NoError(t, err)
	assert.True(t, containsRef(resolved), "external refs are preserved and still detected")
}

/*
Scenario: Rejecting an unresolvable component ref
Given a schema with a $ref to a missing component
When deref is applied
Then an error describing the unresolved ref is returned

Related spec scenarios: RS.MAPI.14
*/
func TestDerefErrorsOnMissingComponent(t *testing.T) {
	t.Parallel()

	schemas := map[string]any{
		"AddExampleRequest": map[string]any{
			"oneOf": []any{map[string]any{"$ref": "#/components/schemas/Missing"}},
		},
	}

	_, err := deref(schemas["AddExampleRequest"], schemas)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "#/components/schemas/Missing")
}

/*
Scenario: Generated Go source exposes the schema and keeps its package
Given resolved schema bytes and a package name
When buildGoSource renders a Go file
Then it contains a recognized "Code generated" header, the target package, and a

	byte literal that unmarshals to the original schema JSON

Related spec scenarios: RS.MAPI.14
*/
func TestBuildGoSource(t *testing.T) {
	t.Parallel()

	schema := []byte(`{"oneOf":[{"type":"object"}]}`)
	output, err := buildGoSource(schema, "server")
	require.NoError(t, err)

	src := string(output)
	assert.Contains(t, src, "// Code generated by gen-control-schema; DO NOT EDIT.")
	assert.Contains(t, src, "package server")
	assert.Contains(t, src, "AddExampleRequestSchemaJSON")
	assert.Contains(t, src, `{\"oneOf\":[{\"type\":\"object\"}]}`)
	require.True(t, strings.HasSuffix(src, "\n"), "generated source must end with a newline")
}

/*
Scenario: Rejecting a self-referential component schema
Given a schema referencing itself through components.schemas
When deref is applied
Then it aborts with a circular-$ref error instead of recursing forever

Related spec scenarios: RS.MAPI.14
*/
func TestDerefRejectsCircularRef(t *testing.T) {
	t.Parallel()

	schemas := map[string]any{
		"AddExampleRequest": map[string]any{
			"$ref": "#/components/schemas/AddExampleRequest",
		},
	}

	_, err := deref(schemas["AddExampleRequest"], schemas)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "circular $ref")
}
